# Generated by Django 3.1 on 2020-08-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200813_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
